[package]
name = "hxo-parser-pug"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
hxo-types = { workspace = true }
serde = { workspace = true }
