[package]
name = "hxo-wit"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.24.0"
hxo-compiler = { path = "../hxo-compiler" }
hxo-ir = { path = "../hxo-ir" }
hxo-types = { path = "../hxo-types" }
serde = "1.0"
