[package]
name = "hxo-target-js"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

description = "JavaScript target for HXO framework"
keywords = ["hxo", "js", "compiler"]
categories = ["compilers"]

[dependencies]
hxo-types.workspace = true
hxo-ir.workspace = true
hxo-source-map.workspace = true
